blank_issues_enabled: false
contact_links:
  - name: noVNC Discussion Group
    url: https://groups.google.com/forum/?fromgroups#!forum/novnc
    about: Please use this group for questions and discussions around noVNC.
